# -*- coding: utf-8 -*-
"""session3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWPJdM1xPmt6pnMvRbQGvOmz1N5PmlAb
"""

import pandas as pd
import numpy as np
np.random.seed(42)

data = {"feature1":[1,2,3,4,5,6]}
df = pd.DataFrame(data)
print(df)

df["feature2"] = np.random.randint(0,100,6)
df

import statistics as ss

data2 = np.random.uniform(100,200,500)
means = ss.mean(data2)
print(means)
# 149.34396291183953

std = ss.stdev(data2)
print(std)

data_new = (data2 - means )/ std

print(min(data_new) , max(data_new) , ss.mean(data_new) , ss.stdev(data_new))

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df = pd.DataFrame({"columns":list(data2)})

df["column_normal"] = scaler.fit_transform(df)

df

